name: Send a Tweet from the Commit Message
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'https')"     
    steps:
      - name: Extract Line with URL as Tweet Message  
        run: |
              commit_string="${{ github.event.head_commit.message }}"
              echo $commit_string | grep -m 1 https* > tweet
              read tweet_message < tweet
              echo "::set-env name=tweet_message::$tweet_message"
      
      - name: Send Tweet       
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ env.tweet_message }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
